default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qulture_challenge_api_development
  username: postgres
  password: postgres
  host: db
  port: 5432

test:
  <<: *default
  database: qulture_challenge_api_test
  username: postgres
  password: postgres
  host: db
  port: 5432

production:
  <<: *default
  database: qulture_challenge_api_production
  username: qulture_challenge_api
  password: <%= ENV["QULTURE_CHALLENGE_API_DATABASE_PASSWORD"] %>
